### Calcualtion of smallest eigenvalue

In [1]:
# importing needed libraries
import numpy as np

# Define the original matrix A
A = np.array([[2, 8, 10],
              [8, 4, 5],
              [10, 5, 7]])

# Calculate the inverse of A
C = np.linalg.inv(A)

# Initialize the power method parameters
max_iterations = 100
tolerance = 1e-6
x_k = np.array([1, 1, 1])  # Initial vector x_0

# Apply the power method to the inverse matrix C
for _ in range(max_iterations):
    # Multiply C by the current vector x_k
    x_k1 = np.dot(C, x_k)
    
    # Normalize the resulting vector
    x_k1_norm = np.linalg.norm(x_k1)
    x_k1 = x_k1 / x_k1_norm
    
    # Check for convergence
    if np.linalg.norm(x_k1 - x_k) < tolerance:
        break
    
    # Update x_k for the next iteration
    x_k = x_k1

# Calculate the dominant eigenvalue of C
largest_eigenvalue_inverse = np.dot(x_k, np.dot(C, x_k)) / np.dot(x_k, x_k)

# The smallest eigenvalue of A is the reciprocal of the largest eigenvalue of C
smallest_eigenvalue_A = 1 / largest_eigenvalue_inverse

# Printing the results
print(f"\nThe inverse matrix C is approximately:\n{C}")
print(f"\nThe largest eigenvalue of the inverse matrix C is approximately: {largest_eigenvalue_inverse}")
print(f"\nThe smallest eigenvalue of the original matrix A is approximately: {smallest_eigenvalue_A}")
print(f"\nThe corresponding eigenvector to this smallest eigenvalue is approximately:\n{x_k}")
print('\nNumber of iterations:')
print(_)


The inverse matrix C is approximately:
[[-7.14285714e-02  1.42857143e-01  0.00000000e+00]
 [ 1.42857143e-01  2.04761905e+00 -1.66666667e+00]
 [-5.28677631e-17 -1.66666667e+00  1.33333333e+00]]

The largest eigenvalue of the inverse matrix C is approximately: 3.398537967587981

The smallest eigenvalue of the original matrix A is approximately: 0.294244174859027

The corresponding eigenvector to this smallest eigenvalue is approximately:
[ 0.03202172  0.7777971  -0.62769919]

Number of iterations:
4
