### Calculation of highest eigenvalue

In [1]:
# importing needed libraries
import numpy as np

# Define the matrix A
A = np.array([[2, 8, 10],
              [8, 4, 5],
              [10, 5, 7]])

# Initialize x_0
x_0 = np.array([1, 1, 1])

# Set a maximum number of iterations
max_iterations = 100

# Set a tolerance for convergence
tolerance = 1e-6

# Begin the power method iterations
x_k = x_0
for _ in range(max_iterations):
    # Multiply A by the current vector x_k
    x_k1 = np.dot(A, x_k)
    
    # Normalize the resulting vector
    x_k1_norm = np.linalg.norm(x_k1)
    x_k1 = x_k1 / x_k1_norm
    
    # Check for convergence
    if np.linalg.norm(x_k1 - x_k) < tolerance:
        break
    
    # Update x_k for the next iteration
    x_k = x_k1

# when converged, calculate the eigenvalue
eigenvalue = np.dot(x_k, np.dot(A, x_k)) / np.dot(x_k, x_k)

# Calculate the inverse of A
C = np.linalg.inv(A)

# Print the inverse matrix C, the highest eigenvalue of A, the corresponding eigenvector, and the no of iterations
print("Inverse matrix C:")
print(C)
print("\nHighest eigenvalue of matrix A:")
print(eigenvalue)
print("\nCorresponding eigenvector:")
print(x_k)
print('\nNumber of iterations:')
print(_)

Inverse matrix C:
[[-7.14285714e-02  1.42857143e-01  0.00000000e+00]
 [ 1.42857143e-01  2.04761905e+00 -1.66666667e+00]
 [-5.28677631e-17 -1.66666667e+00  1.33333333e+00]]

Highest eigenvalue of matrix A:
19.88423602661293

Corresponding eigenvector:
[0.58212832 0.49599457 0.64429497]

Number of iterations:
9
